# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in multiwoven-integrations.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "rubocop", "~> 1.21"

gem "dry-schema"

gem "dry-struct"

gem "dry-types"

gem "byebug"

gem "sequel"

gem "pg"

gem "ruby-odbc", git: "https://github.com/Multiwoven/ruby-odbc.git"

gem "webmock", "~> 3.0"

gem "activesupport"

gem "google-apis-sheets_v4"

gem "google-cloud-bigquery"

gem "restforce", "~> 7.1.0"

gem "slack-ruby-client"

gem "async-websocket", "~> 0.8.0"

gem "git"

gem "hubspot-api-client", "~> 17.2.0"

gem "ruby-limiter"

gem "stripe"

gem "net-sftp"

gem "csv"

gem "aws-sdk-athena"

gem "rubyzip"

gem "faraday"

gem "iterable-api-client"

group :development, :test do
  gem "simplecov", require: false
  gem "simplecov_json_formatter", require: false
end
