import { ModelMethodType } from './types';
import SQLImage from '@/assets/images/SQLQuerySelector.svg';
import TableImage from '@/assets/images/TableSelector.svg';
import DBTImage from '@/assets/images/DBTModelSelector.svg';

export enum ModelMethodName {
  SQLQuery = 'SQL Query',
  TableSelector = 'Table Selector',
  DBTModel = 'dbt Model',
}

export const modelMethods: ModelMethodType[] = [
  {
    image: SQLImage,
    name: ModelMethodName.SQLQuery,
    description: 'Filter, transform, and join your data using a SQL query',
    type: 'sql',
    enabled: true,
  },
  {
    image: TableImage,
    name: ModelMethodName.TableSelector,
    description: 'Read all rows from an existing table or view in your database',
    type: 'select',
    enabled: true,
  },
  {
    image: DBTImage,
    name: ModelMethodName.DBTModel,
    description: 'Use a table or materiaized view generated by dbt',
    type: 'dbt',
    enabled: false,
  },
];
