# frozen_string_literal: true

require "json"
require "dry-struct"
require "dry-schema"
require "dry-types"
require "odbc"
require "sequel"
require "byebug"
require "net/http"
require "uri"
require "active_support/core_ext/hash/indifferent_access"
require "restforce"
require "logger"
require "slack-ruby-client"
require "git"
require "ruby-limiter"
require "hubspot-api-client"
require "google/apis/sheets_v4"
require "stringio"
require "stripe"
require "net/sftp"
require "csv"
require "securerandom"
require "aws-sdk-athena"
require "zip"
require "zendesk_api"
require "faraday"
require "base64"
require "aws-sdk-s3"
require "duckdb"
require "iterable-api-client"
require "aws-sdk-sts"
require "ruby-oci8"
require "aws-sdk-sagemaker"
require "aws-sdk-sagemakerruntime"
require "google/cloud/ai_platform/v1"
require "grpc"
require "MailchimpMarketing"

# Service
require_relative "integrations/config"
require_relative "integrations/rollout"
require_relative "integrations/service"

# Core
require_relative "integrations/core/constants"
require_relative "integrations/core/utils"
require_relative "integrations/core/rate_limiter"
require_relative "integrations/core/fullrefresher"
require_relative "integrations/protocol/protocol"
require_relative "integrations/core/base_connector"
require_relative "integrations/core/source_connector"
require_relative "integrations/core/destination_connector"
require_relative "integrations/core/http_helper"
require_relative "integrations/core/http_client"
require_relative "integrations/core/streaming_http_client"
require_relative "integrations/core/query_builder"

# Source
require_relative "integrations/source/snowflake/client"
require_relative "integrations/source/redshift/client"
require_relative "integrations/source/bigquery/client"
require_relative "integrations/source/postgresql/client"
require_relative "integrations/source/databricks/client"
require_relative "integrations/source/salesforce_consumer_goods_cloud/client"
require_relative "integrations/source/aws_athena/client"
require_relative "integrations/source/clickhouse/client"
require_relative "integrations/source/amazon_s3/client"
require_relative "integrations/source/maria_db/client"
require_relative "integrations/source/oracle_db/client"
require_relative "integrations/source/databrics_model/client"
require_relative "integrations/source/aws_sagemaker_model/client"
require_relative "integrations/source/google_vertex_model/client"
require_relative "integrations/source/http_model/client"
require_relative "integrations/source/open_ai/client"

# Destination
require_relative "integrations/destination/klaviyo/client"
require_relative "integrations/destination/salesforce_crm/client"
require_relative "integrations/destination/facebook_custom_audience/client"
require_relative "integrations/destination/slack/client"
require_relative "integrations/destination/hubspot/client"
require_relative "integrations/destination/google_sheets/client"
require_relative "integrations/destination/airtable/client"
require_relative "integrations/destination/stripe/client"
require_relative "integrations/destination/salesforce_consumer_goods_cloud/client"
require_relative "integrations/destination/sftp/client"
require_relative "integrations/destination/postgresql/client"
require_relative "integrations/destination/zendesk/client"
require_relative "integrations/destination/http/client"
require_relative "integrations/destination/iterable/client"
require_relative "integrations/destination/maria_db/client"
require_relative "integrations/destination/databricks_lakehouse/client"
require_relative "integrations/destination/oracle_db/client"
require_relative "integrations/destination/microsoft_excel/client"
require_relative "integrations/destination/microsoft_sql/client"
require_relative "integrations/destination/mailchimp/client"
require_relative "integrations/destination/ais_data_store/client"

module Multiwoven
  module Integrations
    class Error < StandardError; end
    # Your code goes here...
  end
end
