#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "setup"

namespace = ARGV[0] || "multiwoven-dev"
description = ARGV[1]

begin
  Temporal.register_namespace(namespace, description)
  Temporal.logger.info "Namespace created", { namespace: }
rescue Temporal::NamespaceAlreadyExistsFailure
  Temporal.logger.info "Namespace already exists", { namespace: }
end

loop do
  Temporal.list_custom_search_attributes(namespace:)
  Temporal.logger.info("Namespace is ready", { namespace: })
  break
rescue GRPC::NotFound
  Temporal.logger.info("Namespace not yet found, waiting and retrying", { namespace: })
  sleep 1
  next
end
