name: Deploy main

on:
  push:
    branches:
      - main
    paths:
      - "ui/**"
      - "server/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        env:
          SSH_KEY_BASE64: ${{ secrets.SSH_KEY_BASE64 }}
        run: |
          echo "$SSH_KEY_BASE64" | base64 --decode > ${HOME}/multiwoven-deployments.pem
          chmod 600 ${HOME}/multiwoven-deployments.pem

      - name: Deploy main
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ${HOME}/multiwoven-deployments.pem $SSH_USER@$SSH_HOST << 'EOF'
            cd multiwoven
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF
