name: Deploy main

on:
  # IMPORTANT: Temporary, will delete after workflow successfuly completes.
  workflow_dispatch:
  # Automatically run after either `frontend-docker-build (amd64)`
  # or `server-docker-build (amd64)` successfuly completes.
  # SIDE EFFECT: It will run twice, if both builds were triggered.
  workflow_run:
    workflows: ["frontend-docker-build (amd64)", "server-docker-build (AMD)"]
    branches: ["main"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

env:
  IMAGE_NAME_UI: multiwoven/multiwoven-ui-ee
  IMAGE_NAME_SERVER: multiwoven/multiwoven-server-ee
  IMAGE_TAG: edge

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: multiwoven/helm-charts

      - name: Azure Login
        uses: Azure/login@v2.1.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Gets K8s context
        uses: azure/aks-set-context@v3
        with:
            resource-group: ${{ vars.RESOURCE_GROUP }}
            cluster-name: ${{ vars.CLUSTER_NAME }}

      - uses: azure/setup-helm@v4.2.0
        with:
          version: 'latest'
        id: install

      - name: Deploy main to staging
        env:
          API_HOST: ${{ vars.API_HOST }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          TEMPORAL_HOST: ${{ secrets.TEMPORAL_HOST }}
          TEMPORAL_NAMESPACE: ${{ secrets.TEMPORAL_NAMESPACE }}
          TLS_ADMIN_EMAIL: ${{ secrets.TLS_ADMIN_EMAIL }}
          UI_HOST: ${{ vars.UI_HOST }}
          VITE_API_HOST: ${{ vars.VITE_API_HOST }}
          VITE_BRAND_COLOR: ${{ vars.VITE_BRAND_COLOR }}
          VITE_BRAND_HOVER_COLOR: ${{ vars.VITE_BRAND_HOVER_COLOR }}
          VITE_BRAND_NAME: ${{ vars.VITE_BRAND_NAME }}
          VITE_LOGO_URL: ${{ vars.VITE_LOGO_URL }}
        working-directory: charts/multiwoven
        run: |
          helm upgrade -i multiwoven . \
            --set multiwovenConfig.apiHost=$API_HOST \
            --set multiwovenConfig.dbHost=$DB_HOST \
            --set multiwovenConfig.dbUsername=$DB_USERNAME \
            --set multiwovenConfig.dbPassword=$DB_PASSWORD \
            --set multiwovenConfig.privateRepo=true \
            --set multiwovenConfig.registrySecretName=myregistrykey \
            --set multiwovenConfig.temporalHost=$TEMPORAL_HOST \
            --set multiwovenConfig.temporalNamespace=$TEMPORAL_NAMESPACE \
            --set multiwovenConfig.tlsAdminEmail=$TLS_ADMIN_EMAIL \
            --set multiwovenConfig.tlsCertIssuer="letsencrypt-prod" \
            --set multiwovenConfig.uiHost=$UI_HOST \
            --set multiwovenConfig.viteApiHost=$VITE_API_HOST \
            --set multiwovenConfig.viteBrandName=$VITE_BRAND_NAME \
            --set multiwovenConfig.BrandColor=$VITE_BRAND_COLOR \
            --set multiwovenConfig.BrandHoverColor=$VITE_BRAND_HOVER_COLOR \
            --set multiwovenConfig.viteLogoUrl=$VITE_LOGO_URL \
            --set multiwovenPostgresql.enabled=false \
            --set multiwovenServer.multiwovenServer.image.repository=$IMAGE_NAME_SERVER \
            --set multiwovenServer.multiwovenServer.image.tag=$IMAGE_TAG \
            --set multiwovenUI.multiwovenUI.image.repository=$IMAGE_NAME_UI \
            --set multiwovenUI.multiwovenUI.image.tag=$IMAGE_TAG \
            --set multiwovenWorker.multiwovenWorker.args="{./app/temporal/cli/worker}" \
            --set multiwovenWorker.multiwovenWorker.image.repository=$IMAGE_NAME_SERVER \
            --set multiwovenWorker.multiwovenWorker.image.tag=$IMAGE_TAG \
            --set temporal.enabled=false
          
