name: Ruby Gem

on:
  push:
    branches:
      - main
    paths:
      - "integrations/**"

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      matrix:
        ruby-version: [3.2.0]
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Publish to RubyGems
        working-directory: ./integrations
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
