name: Ruby - Integrations

on:
  push:
    branches:
      - main
    paths:
      - "integrations/**"

  pull_request:
    paths:
      - "integrations/**"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "3.2.0"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Update package list
        run: sudo apt update

      - name: Download and Extract DuckDB ODBC driver
        run: |
            wget -O duckdb.zip https://github.com/duckdb/duckdb/releases/download/v1.0.0/libduckdb-linux-amd64.zip
            unzip duckdb.zip -d libduckdb
            sudo mv libduckdb/duckdb.* /usr/local/include
            sudo mv libduckdb/libduckdb.so /usr/local/lib
            sudo ldconfig /usr/local/lib

      - name: Download and Install Oracle Instant Client
        run: |
          sudo apt-get install -y libaio1 alien
          wget http://yum.oracle.com/repo/OracleLinux/OL7/oracle/instantclient/x86_64/getPackage/oracle-instantclient19.6-basic-19.6.0.0.0-1.x86_64.rpm
          wget http://yum.oracle.com/repo/OracleLinux/OL7/oracle/instantclient/x86_64/getPackage/oracle-instantclient19.6-devel-19.6.0.0.0-1.x86_64.rpm
          sudo alien -i --scripts oracle-instantclient*.rpm
          rm -f oracle-instantclient*.rpm

      - name: Install dependencies
        run: bundle install
        working-directory: ./integrations

      - name: Run the default task
        run: bundle exec rake
        working-directory: ./integrations
