name: server-ci

on:
  push:
    branches: [main]
    paths:
      - "server/**"
  pull_request:
    branches: [main]
    paths:
      - "server/**"

env:
  DB_HOST: localhost
  DB_USERNAME: postgres
  DB_PASSWORD: postgres

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: multiwoven_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0

      - name: Update package list
        run: sudo apt update

      - name: Download and Extract DuckDB ODBC driver
        run: |
            wget -O duckdb.zip https://github.com/duckdb/duckdb/releases/download/v1.0.0/libduckdb-linux-amd64.zip
            unzip duckdb.zip -d libduckdb
            sudo mv libduckdb/duckdb.* /usr/local/include
            sudo mv libduckdb/libduckdb.so /usr/local/lib
            sudo ldconfig /usr/local/lib

      - name: Bundle Install
        run: bundle install
        working-directory: ./server

      - name: Database Setup
        run: bundle exec rake db:create db:schema:load --trace
        working-directory: ./server

      - name: Run RuboCop
        run: bundle exec rubocop
        working-directory: ./server

      - name: Run Tests
        run: bundle exec rspec
        working-directory: ./server

      - name: Install cc-test-reporter
        if: github.event_name == 'push'
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
        working-directory: ./server

      - name: Upload Coverage to Code Climate
        if: github.event_name == 'push'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID_SERVER }}
        run: |
          ./cc-test-reporter before-build
          ./cc-test-reporter after-build --exit-code $?
        working-directory: ./server
