name: server-docker-build (ARM)

on:
  workflow_run:
    workflows: ["server-ci"]
    branches: [main]
    types:
      - completed

env:
  IMAGE_NAME: multiwoven/multiwoven-server
  IMAGE_TAG: edge-arm

jobs:
  build_and_push:
    runs-on: [self-hosted, Linux, ARM64]
    timeout-minutes: 45
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
