name: Cherry-pick CE commit PR from Enterprise to OSS

on:
  workflow_dispatch:
    inputs:
      start_date:
        description: 'Start date (YYYY-MM-DD)'
        required: true
      end_date:
        description: 'End date (YYYY-MM-DD)'
        required: true

jobs:
  cherry-pick-ce-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout OSS repo
        uses: actions/checkout@v2
        with:
          repository: Multiwoven/multiwoven
          ref: main

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure Git
        run: |
          git config --global user.name 'ai-squared'
          git config --global user.email 'developers@squared.ai'

      - name: Add enterprise remote
        run: |
          git remote add enterprise git@github.com:Multiwoven/multiwoven-ee.git
          git fetch enterprise

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create PRs for each CE commit from specified date range
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          START_DATE=${{ github.event.inputs.start_date }}
          END_DATE=${{ github.event.inputs.end_date }}
          echo "Processing commits from $START_DATE to $END_DATE"
          git log enterprise/main --since="$START_DATE 00:00" --until="$END_DATE 23:59" --grep="(CE)" --format="%H" --no-merges | while read sha; do
            AUTHOR_NAME=$(git log -1 --pretty=format:'%an' $sha)
            AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae' $sha)
            COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s' $sha)
            BRANCH_NAME="cherry-pick-ce-commit-${sha}"
            git checkout -b $BRANCH_NAME
            git cherry-pick $sha || {
              echo "Conflict in commit $sha, resolving manually."
              git add .
              git commit -am "Resolve conflict in cherry-pick of $sha and change the commit message"
            }
            git push --force --set-upstream origin $BRANCH_NAME
            PR_TITLE="${COMMIT_MESSAGE}"
            PR_BODY="This PR cherry-picks the CE commit ${sha} from the Enterprise repository. Commit author: ${AUTHOR_NAME} (${AUTHOR_EMAIL})"
            AUTHOR_GH_USERNAME=$(gh api graphql -f query='query { search(query: "${AUTHOR_EMAIL}", type: USER, first: 1) { nodes { ... on User { login } } } }' -q '.data.search.nodes[0].login')
            if [ -n "$AUTHOR_GH_USERNAME" ]; then
              PR_BODY="${PR_BODY}\n\ncc @${AUTHOR_GH_USERNAME}"
              gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base main --head $BRANCH_NAME --assignee "$AUTHOR_GH_USERNAME"
            else
              gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base main --head $BRANCH_NAME
            fi
            git checkout main
            git branch -D $BRANCH_NAME
          done
