name: Build and push Multiwoven UI docker image to Docker Hub (arm64)

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  docker-hub-push-on-merge:
    runs-on: [self-hosted, Linux, ARM64]
    timeout-minutes: 45
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            multiwoven/multiwoven-ui

      - name: Build and push UI Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./ui
          file: ./ui/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}-arm
          labels: ${{ steps.meta.outputs.labels }}-arm