name: Build and push Multiwoven UI docker image to Docker Hub (amd64)

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag to build"
        required: true
  repository_dispatch:
    types: [trigger-docker-build]

jobs:
  docker-hub-push-on-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.tag || github.event.inputs.release_tag }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            multiwoven/multiwoven-ui

      - name: Build and push UI Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./ui
          file: ./ui/Dockerfile
          push: true
          tags: multiwoven/multiwoven-ui:${{ github.event.client_payload.tag || github.event.inputs.release_tag }},multiwoven/multiwoven-ui:latest
          labels: ${{ steps.meta.outputs.labels }}
