name: UI - Validate Workflow

on:
  push:
    branches:
      - main
    paths:
      - "ui/**"
  pull_request:
    branches:
      - main
    paths:
      - "ui/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Use Yarn
        run: npm install -g yarn@latest

      - name: Install dependencies
        run: yarn install
        working-directory: ./ui

      - name: Build Source Code
        run: yarn run build
        working-directory: ./ui

      - name: Lint Source Code
        run: yarn run lint
        working-directory: ./ui
